slug: pytorch
landscapeMemberClasses:
   - name: Platinum Membership
     category: Platinum
   - name: Gold Membership
     category: Gold
   - name: Silver Membership
     category: Silver
   - name: Associate Membership
     category: Associate
project: a092M00001LkQdtQAF
memberSuffix: ' (member)'
landscapeMemberCategory: PyTorch Members
landscapefile: landscape.yml
landscapeProjectsCategory: PyTorch Projects
landscapeProjectsSubcategories:
  - name: Foundation
    category: Foundation
landscapeProjectsLevels:
  - name: Foundation
    level: foundation
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/pytorch
